n = input('digite um valor: ')
print(type(n))
print('é numerico: {}'.format(n.isnumeric()))
print('é alpha: {}'.format(n.isalpha()))
print('é alpha numerico: {}'.format(n.isalnum()))
print('Está em maiúsculas ? {}'.format(n.isupper()))
print('Está minúsculas? {}'.format(n.islower()))
print('Está capitalizado? {}'.format(n.istitle()))